spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(6NYFsI49EJxuJkz2J6efNBcvgoE3IrJuTltwfqm4ZR5rBshWlcOtklfTr1eo0YvlzYCR4oj5+Q5QIvFYNjQJqiA71FhV0jjafjzPtGsAHV7XCQZum4QjXiQHLFaRasag50rbJs+Y9JzHjBF+AO8VlZPl2TGQcUsZKKqE5ZdGes+VbE8A1whStA==)
    username: ENC(WyYk4LMI3u65sr7IMGC0TK++FAi7768n)
    password: ENC(jWAujZXET7lJ51VWnd5D2S3zb+YIc21xac6FmkViGaBOE2JvRL0Gtg==)
  application:
    name: genius-blog-main


genius:
  env:
    author: Genius
    apiSavePath: E:\Project\GeniusWorld\genius-blog-front\src\api
    blogOssPath: geniusblog/img/


assistant:
  service:
    exception:
      handler:
        disables: springWebExceptionHandler

aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: ENC(QGbvtWQEVUXNNdgO6Y+QpASj1gEa6CliRgol9+1wFRErLyLCVtdcgTrq6ho5urHS)
    accessKeySecret: ENC(GoJQI2SxGURuVz3cZgrzE+2UAo97BqdNW6YItt8KkmW4IMnIwg5CYqPI8TGyfdns)
    bucket: ENC(OXOwlT7o1reQuPA5PkVPH4zql7PxPBJ//3vR3/rnSoM=)
